.PHONY: test clean-test

test:
	PYTHONPATH=. python3 -m pytest tests/

test-verbose:
	PYTHONPATH=. python3 -m pytest -v tests/

test-unit:
	PYTHONPATH=. python3 -m unittest discover -s tests

clean-test:
	rm -rf .pytest_cache
	rm -rf __pycache__
	rm -rf tests/__pycache__
	rm -rf .coverage
	rm -rf htmlcov